// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmW0RP7_c8v6nDDaSmvAG4AjMidcq8Ch4',
    appId: '1:1064991589177:web:5d0deced02afea263fdee8',
    messagingSenderId: '1064991589177',
    projectId: 'flutterpractice-371aa',
    authDomain: 'flutterpractice-371aa.firebaseapp.com',
    storageBucket: 'flutterpractice-371aa.firebasestorage.app',
    measurementId: 'G-YY49C4FHXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEuLG7wjSfjaWOf8GfsDAFJhyRdez1Pt4',
    appId: '1:1064991589177:android:5688c1dc7a988e353fdee8',
    messagingSenderId: '1064991589177',
    projectId: 'flutterpractice-371aa',
    storageBucket: 'flutterpractice-371aa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdCpOV7gIm652vpAkLUe0ja7SeIk2vYeU',
    appId: '1:1064991589177:ios:9663849a662e32083fdee8',
    messagingSenderId: '1064991589177',
    projectId: 'flutterpractice-371aa',
    storageBucket: 'flutterpractice-371aa.firebasestorage.app',
    iosBundleId: 'com.example.netflixClone',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdCpOV7gIm652vpAkLUe0ja7SeIk2vYeU',
    appId: '1:1064991589177:ios:9663849a662e32083fdee8',
    messagingSenderId: '1064991589177',
    projectId: 'flutterpractice-371aa',
    storageBucket: 'flutterpractice-371aa.firebasestorage.app',
    iosBundleId: 'com.example.netflixClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmW0RP7_c8v6nDDaSmvAG4AjMidcq8Ch4',
    appId: '1:1064991589177:web:5d0deced02afea263fdee8',
    messagingSenderId: '1064991589177',
    projectId: 'flutterpractice-371aa',
    authDomain: 'flutterpractice-371aa.firebaseapp.com',
    storageBucket: 'flutterpractice-371aa.firebasestorage.app',
    measurementId: 'G-YY49C4FHXM',
  );
}
